name: "Continuous Integration"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"
      - uses: gradle/actions/setup-gradle@v3

      - name: "Run Gradle"
        run: ./gradlew build

